SELECT [A vs B]
      ,[Country]
      ,[Debit year]
      ,[Debit month]
      ,[Debit date]
      ,[Constituent_id]
      ,[Response]
      ,[Payment method]
      ,[iFrequency]
      ,[Amount]
      ,[Last updated]
      ,[Join channel]
  FROM [report].[dbo].[regular]
