SELECT
"재단법인 그린피스" AS 지부,
"" AS 회원번호,
base_MPC.code AS 사용자입력1,
"Lead Conversion" AS 가입경로,
case
  when base_MPC.가입체널 like '%카카오-E%' THEN 'Antarctica_Emoticon'
  else 캠페인명.캠페인영어명
END AS 가입경로상세,
"아니오" AS 탈퇴여부,
IIf([base_MPC].[후원구분]="정기","예","아니오") AS 납부여부,
"10" AS 납부일,
"Normal" AS 회원상태,
"MPC" AS 사용자구분10,
"아니오" AS 납부일시중지여부,
"1개월" AS 납부주기개월,
IIf([base_MPC].[후원구분]="정기","그린피스-정기후원금액","그린피스-일시후원금액") AS 납부구분,
base_MPC.[최종통화일(=기입일)] AS 가입일,
base_MPC.[최종통화일(=기입일)] AS [납부항목-신청일],
base_MPC.후원자명 AS 성명,
base_MPC.주민번호, "" AS [(소득공제)서명],
"" AS [(소득공제)주민번호],
IIf([base_MPC].[납부방법]="CMS",[base_MPC].[예금주/카드주],"") AS 예금주,
IIf([base_MPC].[납부방법]="CMS",[base_MPC].[예금주번호/카드유효기간],"") AS 예금주주민번호,
base_MPC.성별, Mid([base_MPC].[생년월일],1,4) & "-" & Mid([base_MPC].[생년월일],5,2) & "-" & Mid([base_MPC].[생년월일],7,2) AS 생년월일,
base_MPC.납부방법,
base_MPC.납부금액,
base_MPC.[은행/카드사영] AS 은행,
base_MPC.[계좌번호/카드번호] AS 계좌번호,
IIf([base_MPC].[납부방법]="신용카드",[base_MPC].[예금주번호/카드유효기간],Null) AS [(카드)유효기간],
"" AS 예금주정보_추가예금주정보_추가,
"" AS 예금주정보_추가1,
"양력" AS [음력/양력],
IIf([base_MPC].[우편수신여부]="예","자택","수신안함") AS 우편물수신처,
base_MPC.주소 AS 집주소,
base_MPC.상세주소 AS 집주소상세,
base_MPC.우편번호 AS 집우편번호,
base_MPC.휴대전화번호 AS 휴대전화번호,
base_MPC.SMS수신여부 AS SMS수신여부, 
base_MPC.이메일, base_MPC.이메일수신여부, base_MPC.후원구분 AS 최초등록구분,
"개인" AS 등록구분, Mid([base_MPC].[납부시작년월],1,4) & "-" & Mid([base_MPC].[납부시작년월],5,2) AS 납부시작년월,
base_MPC.관심분야, base_MPC.콜내용, base_MPC.기록분류, base_MPC.고객명, base_MPC.이메일, base_MPC.서명일, base_MPC.통화결과, base_MPC.상담사
FROM base_MPC INNER JOIN 캠페인명 ON base_MPC.캠페인 = 캠페인명.캠페인한국명
WHERE (((base_MPC.통화결과)="성공"));
